import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, CheckCircle2, CloudRain, Database, ExternalLink, FileWarning, Layers3, Radio, ShieldAlert, Sparkles } from "lucide-react";
import { DashboardShell } from "@/components/DashboardShell";
import { RiskMap } from "@/components/RiskMap";
import { floodIntelligenceService } from "@/services/api";
import type { FloodDataSummary } from "@shared/flood";

const fallback: FloodDataSummary = { mode: "prototype", updatedAt: null, sources: [{ name: "Bhuvan / NRSC", status: "not_configured", purpose: "Flood hazard, inundation, vulnerability, terrain and water-body layers" }, { name: "IMD", status: "not_configured", purpose: "Rainfall observations, QPF and official weather warnings" }], risk: { score: 39, level: "Moderate", currentRisk: 0, forecastRisk: 0, historicalRisk: 57, modelLabel: "AI-Assisted Flood Risk Score — Prototype", explanation: "Flood risk is moderate because historical flood hazard, water-body exposure, and terrain vulnerability are elevated in the normalized input data.", contributingFactors: [{ label: "Current inundation", value: 0, level: "Low" }, { label: "Current rainfall", value: 0, level: "Low" }, { label: "Rainfall forecast", value: 0, level: "Low" }, { label: "Historical flood hazard", value: 68, level: "Very High" }, { label: "Terrain vulnerability", value: 55, level: "High" }, { label: "Population exposure", value: 58, level: "High" }] }, currentEvents: [] };

const colorFor = (level: string) => level === "Critical" ? "#e65353" : level === "Very High" ? "#e98b42" : level === "High" ? "#d4a63d" : level === "Moderate" ? "#57a681" : "#76988c";

export default function Index() {
  const [summary, setSummary] = useState<FloodDataSummary>(fallback);
  const [serviceState, setServiceState] = useState<"loading" | "available" | "unavailable">("loading");
  const [view, setView] = useState<"Current" | "Forecast" | "30-day history">("Current");

  useEffect(() => {
    floodIntelligenceService.getSummary().then((data) => { setSummary(data); setServiceState("available"); }).catch(() => setServiceState("unavailable"));
  }, []);

  return <DashboardShell><main>
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#f7f9fb] px-5 pb-14 pt-12 sm:px-10 lg:px-14 lg:pb-20 lg:pt-16"><div className="grid-pattern absolute inset-0 opacity-60" /><div className="relative mx-auto max-w-[1240px]"><div className="max-w-[825px]"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#cfe5dc] bg-[#eef8f3] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#337e69]"><span className="text-[13px]">🇮🇳</span> India flood intelligence · prototype</div><h1 className="max-w-[820px] text-[42px] font-extrabold leading-[1.04] tracking-[-.055em] text-slate-950 sm:text-[62px]">Flood intelligence for <span className="text-[#e55252]">a more prepared India.</span></h1><p className="mt-6 max-w-[650px] text-[15px] leading-7 text-slate-500 sm:text-[17px]">A unified, explainable view of flood hazard, weather signals, historical context, and emergency readiness — designed around Bhuvan/NRSC and IMD data services.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => document.getElementById("india-map")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e55252] px-5 text-[12px] font-extrabold text-white shadow-[0_10px_20px_rgba(229,82,82,.18)] transition hover:-translate-y-0.5 hover:bg-[#d94a4d]">Explore India map <ArrowRight size={15} /></button><button onClick={() => document.getElementById("risk-engine")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex h-11 items-center gap-2 rounded-lg border border-slate-200 bg-white px-5 text-[12px] font-extrabold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50">View risk methodology <Sparkles size={15} className="text-[#337e69]" /></button><Link to="/report" className="inline-flex h-11 items-center gap-2 rounded-lg px-3 text-[12px] font-bold text-slate-500 transition hover:text-slate-900">Report an incident <FileWarning size={15} className="text-[#e55252]" /></Link></div></div><div className="mt-12 grid max-w-[680px] grid-cols-2 gap-x-8 gap-y-4 border-t border-slate-200 pt-5 sm:grid-cols-4 lg:absolute lg:bottom-0 lg:right-0 lg:mt-0 lg:w-[440px] lg:border-t-0 lg:pt-0"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">Live feeds</p><p className="mt-1 text-[14px] font-extrabold text-slate-900">Not connected</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">Verified events</p><p className="mt-1 text-[14px] font-extrabold text-slate-900">0 shown</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">Risk model</p><p className="mt-1 text-[14px] font-extrabold text-slate-900">Prototype</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">Coverage</p><p className="mt-1 text-[14px] font-extrabold text-slate-900">India</p></div></div></div></section>
    <section className="border-b border-[#f1d8d4] bg-[#fff8f6] px-5 py-3 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-[1240px] items-start gap-3 text-[11px] leading-5 text-slate-600"><ShieldAlert size={16} className="mt-0.5 shrink-0 text-[#d55b4e]" /><span><strong className="text-slate-800">Live flood-event safeguard:</strong> No active flood event is presented as live until Bhuvan/NRSC and IMD feeds are configured, validated, and time-stamped. This interface currently shows prototype risk context only.</span></div></section>
    <section id="india-map" className="bg-white px-5 py-14 sm:px-10 lg:px-14 lg:py-20"><div className="mx-auto max-w-[1240px]"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="section-kicker">Primary geospatial view</p><h2 className="section-title">India flood intelligence map</h2><p className="section-copy">Turn hazard, inundation, rainfall, warnings, water bodies, and historical areas into a shared operating picture.</p></div><div className="flex rounded-lg border border-slate-200 bg-slate-50 p-1">{(["Current", "Forecast", "30-day history"] as const).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-md px-3 py-2 text-[10px] font-extrabold ${view === item ? "bg-slate-900 text-white shadow-sm" : "text-slate-500"}`}>{item}</button>)}</div></div><RiskMap /><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-slate-200 p-4"><p className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-slate-400"><Radio size={13} /> Current floods</p><p className="mt-3 text-[13px] font-bold text-slate-800">No verified live events shown</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Connect verified Bhuvan and IMD feeds to publish current flood records.</p></div><div className="rounded-xl border border-slate-200 p-4"><p className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-slate-400"><CloudRain size={13} /> Forecast risk</p><p className="mt-3 text-[13px] font-bold text-slate-800">IMD forecast adapter ready</p><p className="mt-1 text-[11px] leading-5 text-slate-500">QPF, rainfall forecasts, and warnings normalize before scoring.</p></div><div className="rounded-xl border border-slate-200 p-4"><p className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-slate-400"><Layers3 size={13} /> Historical intelligence</p><p className="mt-3 text-[13px] font-bold text-slate-800">Bhuvan context adapter ready</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Hazard, vulnerability, terrain, and water-body layers stay available as source context.</p></div></div></div></section>
    <section id="risk-engine" className="border-y border-slate-200 bg-[#f7f9fb] px-5 py-14 sm:px-10 lg:px-14 lg:py-20"><div className="mx-auto grid max-w-[1240px] gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="section-kicker">Transparent model</p><h2 className="section-title max-w-[500px]">AI-assisted flood risk score — prototype.</h2><p className="section-copy max-w-[510px]">A transparent weighted model combines normalized current, forecast, and historical inputs. It is not scientifically validated and is designed to be enhanced with ML trained on historical Indian flood data.</p><div className="mt-7 flex items-end gap-5"><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full border-[10px] border-[#e3efe9] border-t-[#57a681] border-r-[#57a681]"><span className="text-[28px] font-extrabold tracking-[-.06em] text-slate-900">{summary.risk.score}</span><span className="text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">of 100</span></div><div><span className="rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.12em]" style={{ color: colorFor(summary.risk.level), backgroundColor: `${colorFor(summary.risk.level)}18` }}>{summary.risk.level}</span><p className="mt-3 max-w-[290px] text-[12px] leading-5 text-slate-500">Current: {summary.risk.currentRisk}/100 · Forecast: {summary.risk.forecastRisk}/100 · Historical: {summary.risk.historicalRisk}/100</p></div></div><p className="mt-6 flex max-w-[500px] items-start gap-2 rounded-lg border border-slate-200 bg-white p-3 text-[11px] leading-5 text-slate-500"><Sparkles size={14} className="mt-0.5 shrink-0 text-[#337e69]" /><span>{summary.risk.explanation}</span></p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-slate-400">Normalized contributing inputs</p><p className="mt-1 text-[13px] font-bold text-slate-800">No raw Bhuvan or IMD formats reach the client</p></div><Database size={18} className="text-[#337e69]" /></div><div className="mt-6 space-y-4">{summary.risk.contributingFactors.map((factor) => <div key={factor.label}><div className="mb-2 flex items-center justify-between"><span className="text-[12px] font-semibold text-slate-600">{factor.label}</span><span className="text-[10px] font-extrabold uppercase" style={{ color: colorFor(factor.level) }}>{factor.level} · {factor.value}/100</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${factor.value}%`, backgroundColor: colorFor(factor.level) }} /></div></div>)}</div></div></div></section>
    <section className="bg-white px-5 py-14 sm:px-10 lg:px-14 lg:py-20"><div className="mx-auto max-w-[1240px]"><div className="max-w-[680px]"><p className="section-kicker">Data processing architecture</p><h2 className="section-title">Official data in. One flood data model out.</h2><p className="section-copy">Adapters protect the application from changing source formats and keep source-specific data logic out of the browser.</p></div><div className="mt-9 grid gap-4 lg:grid-cols-[1fr_50px_1fr_50px_1.2fr_50px_1fr]"><div className="rounded-xl border border-slate-200 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#337e69]">01 · Sources</p><p className="mt-4 text-[15px] font-extrabold text-slate-900">Bhuvan + IMD</p><p className="mt-2 text-[11px] leading-5 text-slate-500">Hazard, inundation, vulnerability, rainfall, QPF, and warnings.</p></div><ArrowRight className="m-auto hidden text-slate-300 lg:block" /><div className="rounded-xl border border-slate-200 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#337e69]">02 · Adapters</p><p className="mt-4 text-[15px] font-extrabold text-slate-900">Validate & normalize</p><p className="mt-2 text-[11px] leading-5 text-slate-500">Deduplicate, clean, and process geo-spatial context.</p></div><ArrowRight className="m-auto hidden text-slate-300 lg:block" /><div className="rounded-xl border border-[#cfe5dc] bg-[#f3f9f6] p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#337e69]">03 · Common model</p><p className="mt-4 text-[15px] font-extrabold text-slate-900">FloodData</p><p className="mt-2 text-[11px] leading-5 text-slate-500">A source-neutral contract for current, forecast, and historical risk.</p></div><ArrowRight className="m-auto hidden text-slate-300 lg:block" /><div className="rounded-xl border border-slate-200 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#337e69]">04 · Decisions</p><p className="mt-4 text-[15px] font-extrabold text-slate-900">Risk engine</p><p className="mt-2 text-[11px] leading-5 text-slate-500">Explainable score, map layers, and response recommendations.</p></div></div></div></section>
    <section className="bg-[#12232a] px-5 py-14 text-white sm:px-10 lg:px-14"><div className="mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-[1fr_1.2fr]"><div><p className="section-kicker !text-[#72c5a5]">Source readiness</p><h2 className="mt-3 text-[32px] font-extrabold leading-[1.08] tracking-[-.045em] sm:text-[42px]">Built to connect to India’s official intelligence services.</h2><p className="mt-5 max-w-[500px] text-[14px] leading-6 text-slate-400">The UI remains useful and honest when external services are unavailable, while the backend endpoint exposes a normalized API ready for authorized adapters.</p><Link to="/command-center" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-[#e55252] px-5 py-3 text-[12px] font-extrabold text-white transition hover:bg-[#d94a4d]">Open command center <ArrowUpRight size={15} /></Link></div><div className="grid gap-3">{summary.sources.map((source) => <div key={source.name} className="flex gap-4 rounded-xl border border-white/10 bg-white/[.04] p-5"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${source.status === "configured" ? "bg-[#1f4a3d] text-[#80d5b3]" : "bg-white/8 text-slate-400"}`}>{source.status === "configured" ? <CheckCircle2 size={17} /> : <Database size={17} />}</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-[14px] font-extrabold">{source.name}</p><span className="rounded-full bg-white/8 px-2 py-1 text-[9px] font-extrabold uppercase tracking-[.12em] text-slate-400">{source.status.replace("_", " ")}</span></div><p className="mt-2 text-[11px] leading-5 text-slate-400">{source.purpose}</p></div></div>)}<p className="flex items-center gap-2 px-1 text-[10px] font-semibold text-slate-500"><ExternalLink size={12} /> Authorized source endpoints and credentials are required before any live publication.</p></div></div></section>
  </main></DashboardShell>;
}
