import { Bell, CheckCircle2, Clock3, X } from "lucide-react";
import { indiaDisasterEvents } from "@/components/RiskMap";
import { cn } from "@/lib/utils";

export function NotificationPanel({ dark, onClose }: { dark: boolean; onClose: () => void }) {
  return <div className={cn("absolute right-0 top-12 z-[60] w-[min(370px,calc(100vw-2rem))] overflow-hidden rounded-2xl border shadow-[0_18px_50px_rgba(15,30,35,.2)]", dark ? "border-white/10 bg-[#111c24]" : "border-slate-200 bg-white")}>
    <div className={cn("flex items-start justify-between border-b p-4", dark ? "border-white/10" : "border-slate-100")}><div><p className={cn("flex items-center gap-2 text-[12px] font-extrabold", dark ? "text-white" : "text-slate-900")}><Bell size={15} className="text-[#e55252]" /> Recent disasters</p><p className="mt-1 text-[10px] font-semibold text-slate-400">Last 7 days · prototype feed</p></div><button onClick={onClose} className={cn("rounded-md p-1", dark ? "text-slate-400 hover:bg-white/10 hover:text-white" : "text-slate-400 hover:bg-slate-100 hover:text-slate-800")} aria-label="Close notifications"><X size={15} /></button></div>
    <div className="max-h-[370px] overflow-y-auto p-2">{indiaDisasterEvents.map((event) => <div key={event.id} className={cn("rounded-xl p-3", dark ? "hover:bg-white/[.04]" : "hover:bg-slate-50")}><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: event.color }} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className={cn("text-[12px] font-extrabold", dark ? "text-white" : "text-slate-900")}>{event.hazard}</p><span className="rounded-full px-1.5 py-0.5 text-[8px] font-extrabold uppercase tracking-[.08em]" style={{ color: event.color, backgroundColor: `${event.color}18` }}>{event.risk}</span></div><p className={cn("mt-1 text-[10px] font-semibold", dark ? "text-slate-300" : "text-slate-600")}>{event.district}, {event.state}</p><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-[9px] font-semibold text-slate-400"><span className="flex items-center gap-1"><Clock3 size={10} /> {event.date}</span><span className="flex items-center gap-1"><CheckCircle2 size={10} className={event.status === "Active" ? "text-[#e55252]" : "text-[#57a681]"} /> {event.status}</span></div><p className="mt-2 text-[9px] leading-4 text-slate-400">{event.source} · {event.updated.replace("Demo timestamp · ", "")}</p></div></div></div>)}</div>
    <div className={cn("border-t px-4 py-3 text-[9px] leading-4", dark ? "border-white/10 text-slate-500" : "border-slate-100 text-slate-400")}>Demo data only. Verify every event against official emergency communications before taking action.</div>
  </div>;
}
